name: PHPStan

on:
  push:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'


permissions:
  contents: read

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup PHP
        uses: shivammathur/setup-php@8358ee0e2e8afe63c2fb8253d1d52085811ab1e5 # v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@26d8a556604053a9612623447203a691f406fbe6 # v4

      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github
